# Generated by Django 5.0.6 on 2026-06-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Texto do botão')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='Link do botão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Central Pet', max_length=100, verbose_name='Nome da loja')),
                ('slogan', models.CharField(default='Tudo para seu melhor amigo!', max_length=200, verbose_name='Slogan')),
                ('whatsapp_number', models.CharField(default='5561991083675', help_text='Ex: 5561991083675 — sem espaços, traços ou parênteses', max_length=20, verbose_name='WhatsApp (apenas números)')),
                ('phone_number', models.CharField(default='(61) 3201-0015', max_length=20, verbose_name='Telefone fixo')),
                ('instagram_url', models.CharField(default='centralpetoficial', max_length=100, verbose_name='Instagram (usuário, sem @)')),
                ('facebook_url', models.CharField(blank=True, max_length=200, verbose_name='Facebook (URL ou usuário)')),
                ('tiktok_url', models.CharField(blank=True, max_length=100, verbose_name='TikTok (usuário, sem @)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de contato')),
                ('address', models.TextField(default='QNM 34 Conjunto H Lote 01\nCeilândia Sul — Brasília/DF', verbose_name='Endereço completo')),
                ('maps_url', models.URLField(blank=True, help_text='Cole o link de compartilhamento do Google Maps', verbose_name='Link Google Maps')),
                ('opening_hours', models.TextField(default='Seg à Sáb: 8h às 19h\nDomingos: 9h às 13h', verbose_name='Horário de funcionamento')),
                ('delivery_text', models.CharField(default='Entrega rápida e sem taxa para você', max_length=200, verbose_name='Destaque da entrega (navbar/hero)')),
                ('about_text', models.TextField(default='Na Central Pet, seu animal encontra tudo que precisa com o cuidado que merece. Oferecemos serviços completos de Banho & Tosa, Táxi Dog, além de uma linha premium de rações e medicamentos. Nossa entrega é rápida, sem taxa e com o exclusivo Disk Ração para pedidos práticos diretamente no seu WhatsApp.', verbose_name='Texto sobre a loja')),
                ('hero_title', models.CharField(default='Cuidado que seu pet sente, amor que fica.', max_length=200, verbose_name='Título principal (Hero)')),
                ('hero_subtitle', models.TextField(default='Banho & Tosa, Táxi Dog, Rações, Medicamentos e muito mais! Entrega rápida e sem taxa para você.', verbose_name='Subtítulo (Hero)')),
            ],
            options={
                'verbose_name': 'Configuração da Loja',
                'verbose_name_plural': 'Configurações da Loja',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nome do cliente')),
                ('pet_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do pet')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Avaliação (1-5)')),
                ('comment', models.TextField(verbose_name='Depoimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
