# Generated by Django 5.0.6 on 2026-06-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banners/', verbose_name='Imagem'),
        ),
    ]
