# Generated by Django 4.2.30 on 2026-06-05 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('products', '0001_initial'),
        ('core', '0002_banner_image_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('produto_whatsapp', 'Produto para WhatsApp'), ('servico_agendamento_aberto', 'Agendamento aberto'), ('agendamento_enviado', 'Agendamento enviado'), ('disk_racao', 'Disk Ração'), ('whatsapp_geral', 'WhatsApp geral'), ('instagram', 'Instagram')], db_index=True, max_length=40, verbose_name='Tipo')),
                ('nome_produto_snapshot', models.CharField(blank=True, max_length=200, verbose_name='Nome do produto')),
                ('preco_produto_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço do produto')),
                ('categoria_produto_snapshot', models.CharField(blank=True, max_length=100, verbose_name='Categoria do produto')),
                ('nome_servico_snapshot', models.CharField(blank=True, max_length=150, verbose_name='Nome do serviço')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash do IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes', to='products.product', verbose_name='Produto')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Registro de Interação',
                'verbose_name_plural': 'Registros de Interações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo', 'created_at'], name='core_intera_tipo_7d22d5_idx'), models.Index(fields=['produto', 'created_at'], name='core_intera_produto_f54f78_idx'), models.Index(fields=['servico', 'created_at'], name='core_intera_servico_abb40f_idx')],
            },
        ),
    ]
