# Generated by Django 5.0.6 on 2026-06-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Identificador (URL)')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Descrição curta')),
                ('description', models.TextField(verbose_name='Descrição completa')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio se o preço for variável', max_digits=8, null=True, verbose_name='Preço a partir de (R$)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagem')),
                ('icon', models.CharField(blank=True, max_length=20, verbose_name='Ícone (emoji)')),
                ('whatsapp_message', models.TextField(blank=True, help_text="Mensagem enviada automaticamente ao clicar em 'Agendar'. Deixe vazio para usar o padrão.", verbose_name='Mensagem WhatsApp personalizada')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na home')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order', 'name'],
            },
        ),
    ]
